package com.general_hello.commands.OtherEvents;

import com.general_hello.commands.Config;
import com.general_hello.commands.commands.GroupOfGames.MiniGames.ChessStoring;
import com.general_hello.commands.commands.GroupOfGames.MiniGames.MainChessCode;
import com.general_hello.commands.commands.PrefixStoring;
import com.general_hello.commands.commands.Register.Data;
import com.github.bhlangonijr.chesslib.Board;
import net.dv8tion.jda.api.EmbedBuilder;
import net.dv8tion.jda.api.entities.Emoji;
import net.dv8tion.jda.api.events.interaction.ButtonClickEvent;
import net.dv8tion.jda.api.hooks.ListenerAdapter;
import net.dv8tion.jda.api.interactions.components.ActionRow;
import net.dv8tion.jda.api.interactions.components.Button;
import net.dv8tion.jda.api.interactions.components.selections.SelectionMenu;
import org.jetbrains.annotations.NotNull;

import java.awt.*;

public class OnButtonClick extends ListenerAdapter {
    @Override
    public void onButtonClick(@NotNull ButtonClickEvent event) {
        // users can spoof this id so be careful what you do with this
        String[] id = event.getComponentId().split(":"); // this is the custom id we specified in our button
        String authorId = id[0];
        String type = id[1];
        // When storing state like this is it is highly recommended to do some kind of verification that it was generated by you, for instance a signature or local cache

        try {
            event.deferEdit().queue();
        } catch (Exception ignored) {}

        if (!authorId.equals("0000") && !authorId.equals(event.getUser().getId())) {
            event.getMember().getUser().openPrivateChannel().complete().sendMessage(com.general_hello.commands.commands.Emoji.Emoji.ERROR + "You cannot press this button").queue();
            System.out.println("oof");
            return;
        }


        switch (type)
        {
            case "nope":
            case "end":
                event.getHook().deleteOriginal().queue();
                break;
            case "user":
                event.getHook().editOriginalEmbeds(helpCrap(4, event).build()).queue();
                return;
            case "bot":
                event.getHook().editOriginalEmbeds(helpCrap(2, event).build()).queue();
                return;
            case "info":
                event.getHook().editOriginalEmbeds(helpCrap(1, event).build()).queue();
                return;
            case "mod":
                event.getHook().editOriginalEmbeds(helpCrap(3, event).build()).queue();
                return;
            case "music":
                event.getHook().editOriginalEmbeds(helpCrap(6, event).build()).queue();
                return;
            case "game":
                SelectionMenu menu = SelectionMenu.create("menu:class")
                        .setPlaceholder("Choose your age") // shows the placeholder indicating what this menu is for
                        .setRequiredRange(1, 1) // only one can be selected
                        .addOption("Uno", "uno")
                        .addOption("Blackjack", "bj")
                        .addOption("Guess the number", "gn")
                        .addOption("Hangman", "hangman")
                        .addOption("Trivia", "trivia")
                        .addOption("Chess", "chess")
                        .build();

                event.getHook().editOriginalEmbeds(helpCrap(5, event).build()).setActionRows(ActionRow.of(), ActionRow.of()).queue();
                return;
            case "accept":
                String arrow = "<a:arrow_1:862525611465113640>";

                event.getHook().deleteOriginal().queue();
                EmbedBuilder em = new EmbedBuilder().setTitle("Stored data").setFooter("Press the Accept button if you accept the data that will be stored!\n");
                em.setDescription("The bot stores the following data:\n" +
                        arrow + " Reads all sent messages in the server the bot is in.\n" +
                        arrow + " Reads all the messages you sent to the bot.\n" +
                        arrow + " Reads your ignite coins.\n" +
                        arrow + " Reads your user name, profile picture, nitro status, and user id.\n" +
                        arrow + " Reads all the permissions you have on that server.");
                event.getChannel().sendMessageEmbeds(em.build()).setActionRow(
                        Button.primary("0000:yes", "Accept").withEmoji(Emoji.fromEmote("verify", Long.parseLong("803768813110951947"), true))
                ).queue();
                break;
            case "yes":
                event.getHook().deleteOriginal().queue();
                event.getChannel().sendMessage("<a:thanks:863989523461177394> Thank you for accepting the rules and data that will be stored.").queue();
                event.getChannel().sendMessage("<a:question:863989523368247346> For your Ignite Coins balance, may we ask for your first and last, real name? For example, **Nathan Tan** or **John Sy**").queue();
                Data.progress.put(event.getUser(), 1);
                break;
            case "acceptChess":
                event.getMessage().getActionRows().get(0).updateComponent(event.getUser().getId() + ":acceptChess", event.getButton().asDisabled());
                event.getChannel().sendMessage(event.getMember().getAsMention() + " accepted the Chess challenge!\nLoading the game " + com.general_hello.commands.commands.Emoji.Emoji.LOADING).queue();
                MainChessCode.loadBoard(event);
                Board board = new Board();
                ChessStoring.userToBoard.put(event.getUser(), board);
                ChessStoring.userToBoard.put(ChessStoring.userToUser.get(event.getUser()), board);
                event.getInteraction().editButton(event.getButton().asDisabled()).queue();
                break;
            }
    }

    public EmbedBuilder helpCrap (int number, ButtonClickEvent ctx) {
        EmbedBuilder embedBuilder = new EmbedBuilder();
        final long guildID = ctx.getGuild().getIdLong();
        String prefix = PrefixStoring.PREFIXES.computeIfAbsent(guildID, (id) -> Config.get("prefix"));

        switch (number) {
            case 1:
                embedBuilder.setTitle("Information Commands");
                embedBuilder.setColor(Color.YELLOW);
                embedBuilder.addField("1.) Profile Command","`" + prefix + " profile`", false);
                embedBuilder.addField("2.) Server Information Command","`" + prefix + " serverinfo`", false);

                embedBuilder.setFooter("\nType " + prefix + " help [command name] to see what they do");
                break;
            case 2:
                embedBuilder.setTitle("About the Bot Commands");
                embedBuilder.setColor(Color.blue);
                embedBuilder.addField("1.) Uptime Command", "`" + prefix + " uptime`", false);
                embedBuilder.addField("2.) Ping Command", "`" + prefix + " ping`", false);
                embedBuilder.addField("3.) About Command", "`" + prefix + " about`", false);


                embedBuilder.setFooter("\nType " + prefix + " help [command name] to see what they do");
                break;
            case 3:
                embedBuilder.setTitle("Moderation Commands");
                embedBuilder.setColor(Color.red);
                embedBuilder.addField("1.) Set Prefix Command", "`" + prefix + " setprefix`", false);
                embedBuilder.addField("2.) Lockdown Command", "`" + prefix + " lockdown`", false);
                embedBuilder.addField("3.) Un-lockdown Command", "`" + prefix + " unlockdown`", false);
                embedBuilder.addField("4.) Add Meme Command", "`" + prefix + " addmeme`", false);
                embedBuilder.addField("5.) Update Ignite Coins Balance Command", "`" + prefix + " updatecoins`", false);

                embedBuilder.setFooter("\nType " + prefix + " help [command name] to see what they do");
                break;
            case 4:
                embedBuilder.setTitle("User Commands");
                embedBuilder.setColor(Color.CYAN);
                embedBuilder.addField("1.) Calculator Command", "`" + prefix + " calculator`", false);
                embedBuilder.addField("2.) Register Command", "`" + prefix + " register`", false);
                embedBuilder.addField("3.) View rank Command", "`" + prefix + " rank`", false);
                embedBuilder.addField("4.) Show a Joke Command", "`" + prefix + " joke`", false);
                embedBuilder.addField("5.) Show a Meme Command", "`" + prefix + " meme`", false);
                embedBuilder.addField("6.) Animal Fact Command", "`" + prefix + " fact`", false);
                embedBuilder.addField("7.) Weather Lookup Command", "`" + prefix + " weather`", false);
                embedBuilder.addField("8.) Lyric Search Command", "`" + prefix + " lyric`", false);
                embedBuilder.addField("9.) Share code Command (Programming)", "`" + prefix + " sharecode`", false);

                embedBuilder.setFooter("Type " + prefix + " help [command name] to see what they do");
                break;
            case 5:
                embedBuilder.setTitle("Games");
                embedBuilder.setColor(Color.ORANGE);
                embedBuilder.setDescription(com.general_hello.commands.commands.Emoji.Emoji.UNO + " **Uno** - Players take turns matching a card in their hand with the current card shown on top of the deck either by color or number. Special action cards deliver game-changing moments as they help you defeat your opponents.\n\n" +
                        com.general_hello.commands.commands.Emoji.Emoji.BLACKJACK + " **Blackjack** - Blackjack is a card game. The object of blackjack is to be dealt cards with a value of up to but not over 21 and to beat the dealer's hand. ... You place bets with the dealer on the likelihood that your hand will come equal or closer to 21 than will the dealer's.\n\n" +
                        com.general_hello.commands.commands.Emoji.Emoji.NUMBER + " **Guess the Number** - Your goal is to get the same number that the bot selected from 1-100 the bot will inform you if the number is *higher* or *lower*\n\n" +
                        com.general_hello.commands.commands.Emoji.Emoji.USER + " **Hangman** - Hangman is a popular word guessing game where the player attempts to build a missing word by guessing one letter at a time.\n\n" +
                        com.general_hello.commands.commands.Emoji.Emoji.MARK_QUESTION + " **Trivia** - Users will be given a random question and they are to answer it.\n\n" +
                        com.general_hello.commands.commands.Emoji.Emoji.BPAWN + " **Chess** *Soon* - Chess is a game played between two opponents on opposite sides of a board containing 64 squares of alternating colors. Each player has 16 pieces. The goal of the game is to checkmate the other king.");

                embedBuilder.setFooter("Type " + prefix + " help [command name] to see what they do");
                break;
            case 6:
                embedBuilder.setTitle("Music Commands *Temporary* " + com.general_hello.commands.commands.Emoji.Emoji.ERROR);
                embedBuilder.setColor(Color.blue);
                embedBuilder.addField("1.) Play Command", "`" + prefix + " play`", false);
                embedBuilder.addField("2.) Pause Command", "`" + prefix + " pause`", false);
                embedBuilder.addField("3.) Queue Command", "`" + prefix + " queue`", false);
                embedBuilder.addField("4.) Repeat Command", "`" + prefix + " repeat`", false);
                embedBuilder.addField("5.) Resume Command", "`" + prefix + " resume`", false);
                embedBuilder.addField("6.) Skip Command", "`" + prefix + " skip`", false);
                embedBuilder.addField("7.) Volume Command", "`" + prefix + " volume`", false);

                embedBuilder.setFooter("Type " + prefix + " help [command name] to see what they do");
        }
        return embedBuilder;
    }
}
