package com.general_hello.commands.OtherEvents;

import com.general_hello.commands.RPG.RpgUser.RPGUser;
import net.dv8tion.jda.api.events.interaction.ButtonClickEvent;
import net.dv8tion.jda.api.hooks.ListenerAdapter;
import org.jetbrains.annotations.NotNull;

public class OnRPGButtonClick extends ListenerAdapter {
    @Override
    public void onButtonClick(@NotNull ButtonClickEvent event) {
        // users can spoof this id so be careful what you do with this
        String[] id = event.getComponentId().split(":"); // this is the custom id we specified in our button
        String authorId = id[0];

        if (id.length == 1) {
            return;
        }

        String type = id[1];
        // When storing state like this is it is highly recommended to do some kind of verification that it was generated by you, for instance a signature or local cache

        if (!authorId.equals("0000") && !authorId.equals(event.getUser().getId())) {
            System.out.println("oof");
            return;
        }

        switch (type) {
            case "start":
                new RPGUser(event.getUser());
                //some other code
                event.getHook().editOriginal("Successfully started your journey! Good luck soldier!").queue();
                break;
            case "end":
                break;
        }
    }
}